### ISSUE TITLE
Deprecate Place#area (replaced with Place#areas)

### ISSUE THREAD

**Issue by jonmd** [energyquantified/eq-python-client#43]
As some places need more areas, we will gradually replace the `Place#area` field with `Place#areas`. The new field is a list of areas.

(This is needed for gas data, where some places are cross-border interconnectors.)

**Tasks:**

- [x] Introduce `Place#areas`
- [x] Deprecate `Place#area`
- [x] Remove `Place#area`
