### ISSUE TITLE
Update Python Client to match new API features

### ISSUE THREAD

**Issue by komape** [energyquantified/eq-python-client#83]
The following features are missing in the Python Client:

```[tasklist]
### Tasks
- [ ] #43
- [ ] #61
- [ ] #77
- [ ] #81
- [ ] https://github.com/energyquantified/eq-python-client/issues/84
- [ ] https://github.com/energyquantified/eq-python-client/issues/85
- [ ] https://github.com/energyquantified/eq-python-client/issues/93
- [ ] https://github.com/energyquantified/eq-python-client/issues/97
```

**Comment by pfwnicks** [comment]
what about PeriodInstancesAPI.relative?

**Comment by komape** [comment]
@pfwnicks Currently, we're collecting features that found their way into the API but not yet into the Python client. The list is not complete and indeed, relative period instances are missing. I'll add them.

Within the next weeks we'll add the missing features.

**Comment by komape** [comment]
@jonmd There still three tasks open...
